
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.3 EDK_MS3.70d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_IIC_DVI_DEVICE_ID,
		XPAR_IIC_DVI_BASEADDR,
		XPAR_IIC_DVI_TEN_BIT_ADR,
		XPAR_IIC_DVI_GPO_WIDTH
	},
	{
		XPAR_IIC_EEPROM_DEVICE_ID,
		XPAR_IIC_EEPROM_BASEADDR,
		XPAR_IIC_EEPROM_TEN_BIT_ADR,
		XPAR_IIC_EEPROM_GPO_WIDTH
	},
	{
		XPAR_IIC_FMC_LPC_DEVICE_ID,
		XPAR_IIC_FMC_LPC_BASEADDR,
		XPAR_IIC_FMC_LPC_TEN_BIT_ADR,
		XPAR_IIC_FMC_LPC_GPO_WIDTH
	},
	{
		XPAR_IIC_SFP_DEVICE_ID,
		XPAR_IIC_SFP_BASEADDR,
		XPAR_IIC_SFP_TEN_BIT_ADR,
		XPAR_IIC_SFP_GPO_WIDTH
	}
};


