all: bits

bits:
	echo -e "run bits\nexit" | xps -nw system.xmp

clean:
	echo -e "run clean\nexit" | xps -nw system.xmp
	rm -f *.log
	rm -f system.log.bak platgen.opt system_incl.make system.make
	rm -f etc/bitgen.ut
	rm -rf blockdiagram __xps

