#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/data/git/reconos/demos/protocol_graph_generic_3slots/hw/edk/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /opt/Xilinx/14.6/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

FPGA_ARCH = virtex6

DEVICE = xc6vlx240tff1156-1

INTSTYLE = default

XPS_HDL_LANG = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT = 

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst -parallel yes

OBSERVE_PAR_OPTIONS = -error no

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

BRAMINIT_ELF_IMP_FILES =
BRAMINIT_ELF_IMP_FILE_ARGS =

BRAMINIT_ELF_SIM_FILES =
BRAMINIT_ELF_SIM_FILE_ARGS =

SIM_CMD = xterm -e ./isim_system

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s isim


CORE_STATE_DEVELOPMENT_FILES = /opt/Xilinx/14.6/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/proc_common_pkg.vhd \
pcores/reconos_v3_00_b/hdl/vhdl/reconos_pkg.vhd \
pcores/ana_v1_00_a/hdl/vhdl/anaPkg.vhd \
pcores/ana_v1_00_a/hdl/vhdl/../../../ana_v1_00_a/hdl/vhdl/packetDecoder.vhd \
pcores/ana_v1_00_a/hdl/vhdl/../../../ana_v1_00_a/hdl/vhdl/packetEncoder.vhd \
pcores/hwt_pr_v1_00_a/hdl/vhdl/hwt_pr.vhd

WRAPPER_NGC_FILES = implementation/system_hwt_pr_0_wrapper.ngc \
implementation/system_hwt_pr_1_wrapper.ngc \
implementation/system_hwt_pr_2_wrapper.ngc \
implementation/system_mb_plb_wrapper.ngc \
implementation/system_rs232_uart_1_wrapper.ngc \
implementation/system_ddr3_sdram_wrapper.ngc \
implementation/system_flash_ce_inverter_wrapper.ngc \
implementation/system_pcie_diff_clk_wrapper.ngc \
implementation/system_clock_generator_0_wrapper.ngc \
implementation/system_mdm_0_wrapper.ngc \
implementation/system_proc_sys_reset_0_wrapper.ngc \
implementation/system_xps_intc_0_wrapper.ngc \
implementation/system_and_gate_wrapper.ngc \
implementation/system_xps_timer_0_wrapper.ngc \
implementation/system_hwt_s2h_0_wrapper.ngc \
implementation/system_hwt_h2s_0_wrapper.ngc \
implementation/system_hwt_ethernet_test_0_wrapper.ngc \
implementation/system_noc_rst_block_0_wrapper.ngc \
implementation/system_fsl_v20_0a_wrapper.ngc \
implementation/system_fsl_v20_0b_wrapper.ngc \
implementation/system_fsl_v20_1a_wrapper.ngc \
implementation/system_fsl_v20_1b_wrapper.ngc \
implementation/system_fsl_v20_2a_wrapper.ngc \
implementation/system_fsl_v20_2b_wrapper.ngc \
implementation/system_fsl_v20_3a_wrapper.ngc \
implementation/system_fsl_v20_3b_wrapper.ngc \
implementation/system_fsl_v20_4a_wrapper.ngc \
implementation/system_fsl_v20_4b_wrapper.ngc \
implementation/system_fsl_v20_5a_wrapper.ngc \
implementation/system_fsl_v20_5b_wrapper.ngc \
implementation/system_fsl_v20_6a_wrapper.ngc \
implementation/system_fsl_v20_6b_wrapper.ngc \
implementation/system_fsl_v20_7a_wrapper.ngc \
implementation/system_fsl_v20_7b_wrapper.ngc \
implementation/system_fifo32_0b_wrapper.ngc \
implementation/system_fifo32_1b_wrapper.ngc \
implementation/system_fifo32_2b_wrapper.ngc \
implementation/system_fifo32_3b_wrapper.ngc \
implementation/system_fifo32_4b_wrapper.ngc \
implementation/system_fifo32_5b_wrapper.ngc \
implementation/system_fifo32_0a_wrapper.ngc \
implementation/system_fifo32_1a_wrapper.ngc \
implementation/system_fifo32_2a_wrapper.ngc \
implementation/system_fifo32_3a_wrapper.ngc \
implementation/system_fifo32_4a_wrapper.ngc \
implementation/system_fifo32_5a_wrapper.ngc \
implementation/system_fifo32_arbiter_0_wrapper.ngc \
implementation/system_fifo32_burst_converter_0_wrapper.ngc \
implementation/system_mmu_0_wrapper.ngc \
implementation/system_xps_mem_0_wrapper.ngc \
implementation/system_proc_control_0_wrapper.ngc \
implementation/system_gnd2int_0_wrapper.ngc \
implementation/system_xps_sysace_0_wrapper.ngc \
implementation/system_xps_hwicap_0_wrapper.ngc \
implementation/system_noc_switch_0_wrapper.ngc \
implementation/system_noc_switch_1_wrapper.ngc \
implementation/system_noc_switch_2_wrapper.ngc \
implementation/system_microblaze_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT)
