# TODO: refactorize

all:
	cd configd && make
	cd fbctl && make
	cd fbprop && make
	cd fbviz && make
	cd readpvr && make
	cd sensord && make
	cd sensord/plugins && make
	cd timedb && make
	cd vlink && make

clean:
	cd configd && make clean
	cd fbctl && make clean
	cd fbprop && make clean
	cd fbviz && make clean
	cd readpvr && make clean
	cd sensord && make clean
	cd sensord/plugins && make clean
	cd timedb && make clean
	cd vlink && make clean
