#!/bin/sh

/bin/echo "Starting rcS..."
/bin/echo "++ Creating device points"
/bin/mkdir -p /dev/pts
/bin/mount -t devpts devpts /dev/pts
/bin/mkdir -p /lib/modules/`uname -r`/
/bin/echo "++ Mounting filesystem"
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
/bin/mount -t tmpfs none /tmp
/bin/echo "++ Loading system loggers"
/sbin/syslogd
/sbin/klogd
echo "++ Microblaze CPU info"
cat /proc/cpuinfo
/bin/echo "... rcS Complete"
