CFLAGS	=	-O3 -g -Wall -fstack-protector -fpie -std=gnu99 -D_FORTIFY_SOURCE=2 -D_REENTRANT -march=native -mtune=native
CC	=	gcc
AR	=	ar

all: timedb_create timedb_update timedb_dump timedb_get

timedb_get:

timedb_dump:

timedb_create:

timedb_update:

clean:
	rm -f *.o timedb_create timedb_update timedb_dump timedb_get
