CFLAGS	=	-O2 -g -Wall
#CC	=	microblaze-unknown-linux-gnu-gcc
#AR	=	microblaze-unknown-linux-gnu-ar

all: timedb_create timedb_update timedb_dump timedb_get

timedb_get:

timedb_dump:

timedb_create:

timedb_update:

clean:
	rm -f *.o timedb_create timedb_update timedb_dump timedb_get
