CFLAGS	=	-O2 -g -Wall -I../../../../linux/net/ -I../../../../linux/tools/configd/
CC	=	microblaze-unknown-linux-gnu-gcc
AR	=	microblaze-unknown-linux-gnu-ar

#file_transfer:

all: pr_demo_reconfig

pr_demo_reconfig: pr_demo_reconfig.o

clean:
	rm -f *.o pr_demo_reconfig
