
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.2 EDK_P.28xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xemaclite.h"

/*
* The configuration table for devices
*/

XEmacLite_Config XEmacLite_ConfigTable[] =
{
	{
		XPAR_ETHERNET_MAC_DEVICE_ID,
		XPAR_ETHERNET_MAC_BASEADDR,
		XPAR_ETHERNET_MAC_TX_PING_PONG,
		XPAR_ETHERNET_MAC_RX_PING_PONG,
		XPAR_ETHERNET_MAC_INCLUDE_MDIO,
		XPAR_ETHERNET_MAC_INCLUDE_INTERNAL_LOOPBACK
	}
};


