#!/bin/sh

# Copyright 2012 Markus Happe <markus.happe@upb.de>
# Copyright 2012 Daniel Borkmann <daniel.borkmann@tik.ee.ethz.ch>

# Downloads bitstreams or ELF files to XUP FPGA

DOW_BIT=$RECONOS/tools/download_bitstream.sh
DOW_ELF=$RECONOS/tools/download_executable.sh

if [ -z $1 ]; then
	echo "USAGE: dow bitstream.bit [jtag_chain_position]"
	echo "             OR"
	echo "       dow executable.elf [cpu nr]"
	echo ""
	echo "Standard jtag chain position is 3 (XUP)"
	exit 1
fi
if [ -z $RECONOS_BOARD ]; then
	RECONOS_BOARD=xup
fi
if [ "$RECONOS_BOARD" = "ml403" ]; then
	POS=2
elif [ "$RECONOS_BOARD" = "xup" ]; then
	POS=3
elif [ "$RECONOS_BOARD" = "ml605" ]; then
	POS=2
else
	echo "Unsupported board or no board specified."
	exit 1
fi
if [ ! -z $2 ]; then
	POS=$2
fi

echo "Using JTAG chain position $POS."

if [ "`file $1 | grep \"BIT\"`" ]; then
	echo "It's a bitfile!"
	$DOW_BIT $1 $POS
elif [ "`file $1 | grep \"ELF\"`" ]; then
	echo "It's an executable!"
	$DOW_ELF $1 $2
else
	echo "Neither an executable nor a bitfile!"
	exit 1
fi
