#!/bin/sh

#repo_name=linux-2.6-xlnx
#commit=f5f537684e5914782e16b00de168c7cebb4a6fcb
#rem_location=git://git.xilinx.com/$repo_name.git

repo_name=linux
commit=HEAD
rem_location=git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/$repo_name.git
own_location=~
cur_location=`pwd`

echo "Cloning into $repo_name ... this can take a while!"
if [ -e $own_location/$repo_name ]
then
	rm -rf $own_location/$repo_name
fi
cd $own_location/
git clone $rem_location
cd $repo_name
git checkout -b reconos $commit
cd $cur_location
