# TODO: refactorize

all:
	cd drivers/fsl_driver && make
	cd drivers/getpgd && make
	cd lana && make
	cd reconos/libreconos-us && make
	cd reconos/libreconos-ks && make
	cd tools && make

clean:
	cd drivers/fsl_driver && make clean
	cd drivers/getpgd && make clean
	cd lana && make clean
	cd reconos/libreconos-us && make clean
	cd reconos/libreconos-ks && make clean
	cd tools && make clean
