
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xhwicap.h"

/*
* The configuration table for devices
*/

XHwIcap_Config XHwIcap_ConfigTable[] =
{
	{
		XPAR_AXI_HWICAP_0_DEVICE_ID,
		XPAR_AXI_HWICAP_0_BASEADDR,
		XPAR_AXI_HWICAP_0_ICAP_DWIDTH,
		XPAR_AXI_HWICAP_0_MODE
	}
};


