
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.2 EDK_P.28xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmpmc.h"

/*
* The configuration table for devices
*/

XMpmc_Config XMpmc_ConfigTable[] =
{
	{
		XPAR_DDR3_SDRAM_DEVICE_ID,
		XPAR_DDR3_SDRAM_MPMC_BASEADDR,
		XPAR_DDR3_SDRAM_MPMC_HIGHADDR,
		XPAR_DDR3_SDRAM_MPMC_CTRL_BASEADDR,
		XPAR_DDR3_SDRAM_INCLUDE_ECC_SUPPORT,
		XPAR_DDR3_SDRAM_USE_STATIC_PHY,
		XPAR_DDR3_SDRAM_PM_ENABLE,
		XPAR_DDR3_SDRAM_MEM_DATA_WIDTH,
		XPAR_DDR3_SDRAM_MEM_PART_NUM_BANK_BITS,
		XPAR_DDR3_SDRAM_MEM_PART_NUM_ROW_BITS,
		XPAR_DDR3_SDRAM_MEM_PART_NUM_COL_BITS,
		XPAR_DDR3_SDRAM_MEM_DQS_WIDTH,
		XPAR_DDR3_SDRAM_MPMC_CLK0_PERIOD_PS
	}
};


